name: dev-benches

services:
  flutter-bench:
    env_file: .env
    image: flutter-bench:${USER:-brett}
    container_name: flutter-bench
    command: sleep infinity
    working_dir: /workspace
    tty: true
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - FLUTTER_ROOT=/opt/flutter
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - ANDROID_HOME=/opt/android-sdk
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
